config/routes.rb
Planb::Application.routes.draw do

  resources :locations

  resources :plans do
    resources :reactions
  end

  resources :users

  resources :pages
  
  
  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout
  match "/map" => "plans#index", :as => :map
  
  root :to => "users#dashboard"
  
  
  

end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  belongs_to :user
  has_many :reactions, :dependent => :destroy
  has_many :attendees, :through => :reactions, :source => :user
  
  validates_presence_of :title, :description, :starts_at, :address, :user_id
  before_save :cleanup
  
  scope :upcoming, lambda { 
      where("plans.starts_at IS NOT NULL AND plans.starts_at >= ?", Time.zone.now)
    }
  named_scope :descending, :order => "starts_at DESC"
  named_scope :ascending, :order => "starts_at ASC"
  
  acts_as_gmappable

  def gmaps4rails_address
    address
  end
  
  def gmaps4rails_infowindow
    "<h1>#{self.title}</h1><p><a href=""/plans/#{self.id}"">view details</a></p>"
  end
  
  private
  
  def cleanup
      self[:title] = self[:title].capitalize
      self[:description] = self[:description].capitalize  
      self[:address] = self[:address].capitalize      
  end
end

app/models/reaction.rb
class Reaction < ActiveRecord::Base
  belongs_to :user
  belongs_to :plan
  
  named_scope :positive, where(:attending => true)
  named_scope :negative, where(:attending => false)
  
  scope :mine, lambda {|u| where(:user_id => u) }
  
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :plans, :dependent => :destroy
    has_many :reactions, :dependent => :destroy
    def self.create_with_omniauth(auth)
      create! do |user| #een block aan create! hangen kan je bij de user voordat ie in de db word opgeslagen.
        user.provider = auth["provider"]
        user.uid = auth["uid"]
        user.name = auth["user_info"]["name"]
        user.email = auth["user_info"]["email"]
        user.image_uri = auth["user_info"]["image"]
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  
  private
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def login
  end
  def dashboard
  end
  def detail
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController

  def index
    @json = Plan.upcoming.to_gmaps4rails
    
    respond_to do |format|
      format.html
    end
  end
  
  def new
    @plan = Plan.new
    @plan.user = current_user
    
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def create
    @plan = Plan.new(params[:plan])
    @plan.user = current_user
  
    respond_to do |format|
      if @plan.save
        format.html { redirect_to root_path, :notice => 'Plan was successfully created.' }
      else
        format.html { render :action => "new" }
      end
    end
  end
  
  def show
    @plan = Plan.find(params[:id])
    #@reactions = @plan.reactions
  end
  
  def edit
    @plan = Plan.find(params[:id])
  end
  
  def update
    @plan = Plan.find(params[:id])
    respond_to do |format|
      if @plan.update_attributes(params[:plan])
        format.html { redirect_to plan_path(@plan), :notice => 'Plan was successfully updated.' }
      else
        format.html { render :action => "edit" }
      end
    end
  end
  
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
  def new
    
    # raise params['a']
    
    if params['a']
      @reaction = Reaction.new
      @plan = Plan.find(params[:plan_id])
      @reaction.user = current_user
      @reaction.plan = @plan
      
      @reaction.message = ''
      
      if params['a'] == 'yes'
           #reactie toevoegen met een yes
           @reaction.attending = true
      else
          #reactie toevoegen met een no
          @reaction.attending = false
      end
      respond_to do |format|
        if @reaction.save
          format.html { redirect_to plan_path(@plan), :notice => 'Thanks for sharing!' }
        else
          format.html { redirect_to plan_path(@plan), :notice => 'Oops, something went wrong.' }
        end
      end
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    # om te kijken wat er in de file zit
    # raise request.env["omniauth.auth"].to_yaml
    
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Welcome!"
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "See you later, bye!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @User = User.new
  end
  def dashboard
    # alle plannen van de current_user ophalen en klaarzetten voor de view
    @plans = Plan.where(:user_id => current_user).ascending
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendees/_attendee.html.erb
<div class="attendee-item">
	<%= image_tag(attendee.image_uri, :class => 'attendee-img') %>
	<%= attendee.name %>
	<%= attendee.reaction.attending %>
</div>

app/views/layouts/_meta.html.erb
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0;">
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-touch-fullscreen" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  <link rel="apple-touch-startup-image" href="images/loading.png" />
  <link rel="apple-touch-icon" href="images/icon.png" />
	<link rel="icon" type="image/png" id="favicon" href="images/icon16.png"/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PlanB</title>
  <%= stylesheet_link_tag 'reset.css', 'application.css' %>
  <%= javascript_include_tag :defaults, 'gmaps4rails.base.js', 'gmaps4rails.googlemaps.js' %>
  <%= csrf_meta_tag %>
  <%= render "layouts/meta"%>
  <%= yield :head %>
</head>
<body>
	<div id="container">
		<div id="app-bar">
		  <div id="action-left">
		    <%= yield :nav_action_left %>
		  </div>
		  <div id="action-right">
		    <%= yield :nav_action_right %>
		  </div>
		  <div id="logo">
		    <%= link_to image_tag("planb-logo-pink.png", :id => 'planblogo'), root_path %>
		  </div>

		</div>
		<% flash.each do |name, msg| %>
			<%= content_tag :div, msg, :id => "flash_#{name}" %>
		<% end %>
		<div id="content">
			<% if !current_user %>
				<%= link_to(image_tag("fb-connect-large.png"), "/auth/facebook", :id => 'fb-button') %>
			<% else %>
				<%= yield %>
			<% end %>
		</div>
	</div>
	<%= yield :scripts %>
</body>
</html>

app/views/pages/dashboard.html.erb
<h1 id="dashboard">Dashboard</h1>

app/views/pages/detail.html.erb
<h1 id="detail_page">Detail Page</h1>

app/views/pages/login.html.erb
<h1 id="logo-plan-b">Logo Plan B</h1>
<div id="login-form">
  <form id="login" action="" method="post" accept-charset="utf-8">      
    <input type="email" name="email" placeholder="Email">

    <input type="password" name="password" placeholder="Password">
    
    <input type="submit" name="submit" value="Log in" id="submit" class="button">
  </form>
</div> <!-- end of login-form -->

app/views/pages/welcome.html.erb
<div class="menu">
	<span class="active">Events</span>
	<span>Groups</span>
	<span style="float:right;margin-right: 0;">Logout</span>
	<div style="clear:both;"></div>
</div>
<div class="event_container">
	<div class="event_list_header">
		<span class="column_header" style="width:30px;">Datum</span>
		<span class="column_header" style="width:100%;padding-left:45px;">Plan</span>
		<span class="column_header" style="width: 75px;float:right;">Smiles</span>
	</div>
	<div class="event_item">
		<div class="date">Aug 22 2011</div>
		<div class="description">Potje Paintballen<br/><span class="view"><a href="#">Bekijk plan</a></span></div>
		<div class="smiles">1+ 2-</div>
		<div style="clear:both;"></div>
	</div>
	<div class="event_item selected">
		<div class="date">Aug 27 2011</div>
		<div class="description">A2 Challenge<br/><span class="view"><a href="#">Bekijk plan</a></span></div>
		<div class="smiles">10+ 21-</div>
		<div style="clear:both;"></div>
	</div>
	<div class="event_item">
		<div class="date">Dec 12 2011</div>
		<div class="description">Kerstmis inkopen<br/><span class="view"><a href="#">Bekijk plan</a></span></div>
		<div class="smiles">3+ 5-</div>
		<div style="clear:both;"></div>
	</div>
</div>

app/views/plans/_form.html.erb
<%= form_for(@plan) do |f| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% @plan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Title" %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label "Description" %><br />
    <%= f.text_area :description, :rows => 5 %>
  </div>
  <div class="field">
    <%= f.label "When" %><br />
    <%= f.datetime_select :starts_at %>
  </div>
<div class="field">
    <%= f.label "Address" %><br />
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit "Save my plan" %>
  </div>
<% end %>

app/views/plans/_plan.html.erb
<div class="plan-item <%= cycle('odd', 'even') %> clearfix">
  	<div class="calendar">
    	<time datetime="<%= plan.starts_at.to_s %>">
      		<div class="month">
				<%= plan.starts_at.strftime( "%b" ) %>
      		</div>
      		<div class="day">
        		<%= plan.starts_at.day %>
      		</div>
    	</time>
  	</div>
	<div class="linkr">
		<%= link_to "", plan_path(plan) %> <!-- vervangen door een arrow img -->
	</div>
  	<div class="desc">
  		<h3 style="display:inline;"><%= plan.title %></h3>
			<span class="when">
				<% if Time.now > plan.starts_at %>
				 <%= distance_of_time_in_words(Time.now, plan.starts_at) %> ago
				<% else %>
				 in <%= distance_of_time_in_words(Time.now, plan.starts_at) %>
				<% end %>
	  		</span>
			<div class="emotion">
				<%= image_tag 'emoticon_smile.png', :class => 'emoticon' %> <%= plan.reactions.positive.length %>
				<%= image_tag 'emoticon_unhappy.png', :class => 'emoticon' %> <%= plan.reactions.negative.length %>
			</div>
  	
	
  		<p><%= plan.description.truncate(95,:separator => ' ',:omission => "...") %></p>
		<span class="address">
			<%= image_tag('map.png') %> <%= plan.address %>
		</span>
		
  	</div>
	
</div>

app/views/plans/edit.html.erb
<% content_for :nav_action_left do %>
  <% if current_user %>	
	  <%= link_to "back", plan_path(@plan), :class => 'nav-button' %>
	<% end %>
<%end%>
<% content_for :nav_action_right do %>
  <% if current_user %>	
	  <%= link_to "delete", plan_path(@plan), :class => 'nav-button' %>
	<% end %>
<%end%>
<%= render 'form' %>

app/views/plans/index.html.erb
<% content_for :nav_action_left do %>
  <% if current_user %>	
	  <%= link_to "profile", root_path, :class => 'nav-button' %>
	<% end %>
<%end%>
<%= gmaps("map_options" => { "mapTypeControl" => false, "detect_location" => true, "center_on_user" => true, "zoom" => 11, "auto_zoom" => false },"markers" => { "data" => @json }) %>

app/views/plans/new.html.erb
<% content_for :nav_action_left do %>
  <% if current_user %>	
	  <%= link_to "back", root_path(), :class => 'nav-button' %>
	<% end %>
<%end%>
<%= render 'form' %>

app/views/plans/show.html.erb
<% content_for :nav_action_left do %>
  <% if current_user %>	
	  <%= link_to "back", root_path(), :class => 'nav-button' %>
	<% end %>
<%end%>
<% content_for :nav_action_right do %>
  <% if current_user %>	
	  <%= link_to "edit", edit_plan_path(@plan), :class => 'nav-button' %>
	<% end %>
<%end%>

<div class="map-image clearfix">
	<%= image_tag "http://maps.google.com/maps/api/staticmap?size=100x100&sensor=false&zoom=11&markers=#{@plan.latitude}%2C#{@plan.longitude}", :id => "location-small" %>
</div>

<header class="clearfix">
<h2><%= @plan.title %></h2>
<span class="when">
	<% if Time.now > @plan.starts_at %>
		<%= distance_of_time_in_words(Time.now, @plan.starts_at) %> ago, by <%= @plan.user.name %>
	<% else %>
		in <%= distance_of_time_in_words(Time.now, @plan.starts_at) %>, by <%= @plan.user.name %>
	<% end %>
</span>
<div class="emotion">
	<%= image_tag 'emoticon_smile.png', :class => 'emoticon' %> <%= @plan.reactions.positive.length %>
	<%= image_tag 'emoticon_unhappy.png', :class => 'emoticon' %> <%= @plan.reactions.negative.length %>
</div>
<div id="reaction">
  <% if @plan.reactions.mine(current_user).length == 0 %>
    <h3>Wanna go?</h3>
	  <%=link_to 'Yes', new_plan_reaction_path(@plan, :a => 'yes'), :class => 'light-button' %> 
	  <%=link_to 'No', new_plan_reaction_path(@plan, :a => 'no'), :class => 'light-button' %>
	<% else %>
	  <!-- If attending => you're attending else ... -->
  <% end %>
</div>
</header>
<div id="reactions">
	<h2>Description</h2>
<p><%= @plan.description %></p>
</div>
<div id="reactions">
	<h2>Reactions</h2>
	<%= render @plan.reactions %>
</div>

app/views/reactions/_reaction.html.erb
<div class="reaction-item">
	<%= image_tag(reaction.user.image_uri, :class => 'attendee-img') %>
	<%= reaction.user.name %>
	
	<% if reaction.attending == true %>
		<%= image_tag 'emoticon_smile.png', :class => 'emoticon', :style => 'float:right;' %>
	<% else %>
		<%= image_tag 'emoticon_unhappy.png', :class => 'emoticon', :style => 'float:right;' %>
	<% end %>
</div>

app/views/users/dashboard.html.erb
<% content_for :nav_action_right do %>
  <% if current_user %>	
	  <%= link_to "new", new_plan_path, :class => 'nav-button' %>
	<% end %>
<%end%>
<% content_for :nav_action_left do %>
  <% if current_user %>	
	  <%= link_to "map", map_path, :class => 'nav-button' %>
	<% end %>
<%end%>
<div id="info" class="clearfix">
  <% if current_user %>
  <%= image_tag(current_user.image_uri, :class => 'user-img') %>
  <h2><%= current_user.name %></h2>
  <%= link_to "Sign out", signout_path, :id => 'signout' %>
  <% end %>
</div>

<div id="plans">
  	<div id="filters"><%=link_to 'yours', '#', :class => 'light-button' %> <%=link_to 'all', '#', :class => 'light-button' %></div>
	<h2>Plans</h2>
  	<% if Plan.count == 0 %>
    	<div class="plan-item clearfix">
      		<div class="linkr">
    			<%= link_to "", new_plan_path %> <!-- vervangen door een arrow img -->
    		</div>
      		<p>You've got no plans. Tap here to start planning!</p>
      		<p><a href="#">Need help?</a></p>
    	</div>
  	<% else %>
		<%= render @plans %>
	<% end %>
</div>